---

- name: "Configure kernel parameters."
  ansible.builtin.copy:
    src: "sysctl.conf"
    dest: "/etc/sysctl.d/50-{{ application_username }}.conf"
    mode: "0644"
  notify:
    - "reload sysctl"
